_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.2
            "8":
                - 3
                - 5
            "12": 0.19.2
            "13": windows-amd64
batch_size:
    value: 16
epoch:
    value: 10
lr:
    value: 0.0002
sampling_rate:
    value: 0.75
shape:
    value: "32_64"
